/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
}
// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:
// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:
// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next:// Default ignores of eslint-config-next: